name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest changes
        run: |
          cd /var/www/nfox
          git pull origin main
